/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

type RegistryItemWithComponent = RegistryItem & {
  component: React.LazyExoticComponent<React.ComponentType<any>>;
};

export const Index: Record<string, RegistryItemWithComponent> = {
  "avatar-stack": {
    name: "avatar-stack",
    type: "registry:ui",
    title: "Avatar Stack",
    description: "A component that stacks and overlaps a list of avatars.",
    registryDependencies: ["TODO:/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/ui/avatar-stack.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/ui/avatar-stack");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  heading: {
    name: "heading",
    type: "registry:ui",
    title: "Heading",
    description: "Pending",
    registryDependencies: ["TODO:/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/ui/heading.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/ui/heading");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  marquee: {
    name: "marquee",
    type: "registry:ui",
    title: "Marquee",
    description:
      "A component that displays a list of items in a horizontal or vertical scrolling motion.",
    registryDependencies: ["TODO:/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/ui/marquee.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/ui/marquee");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  tagline: {
    name: "tagline",
    type: "registry:ui",
    title: "Tagline",
    description: "A component that displays a tagline with different variants.",
    registryDependencies: ["TODO:/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/ui/tagline.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/ui/tagline");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "page-heading": {
    name: "page-heading",
    type: "registry:component",
    title: "Page Heading",
    description: "",
    registryDependencies: ["TODO:/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/components/page-heading.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/components/page-heading");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "placeholder-logo": {
    name: "placeholder-logo",
    type: "registry:component",
    title: "Placeholder Logo",
    description:
      "A component for that can be replaced with your brand's main logo. This component ensures layouts stay consistent before brand assets are applied.",
    registryDependencies: ["TODO:/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/components/placeholder-logo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/components/placeholder-logo");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "profile-card": {
    name: "profile-card",
    type: "registry:component",
    title: "Profile Card",
    description:
      "An extension of the avatar component with more details on the individual. Good for blog posts etc.",
    registryDependencies: ["avatar", "TODO:/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/components/profile-card.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/components/profile-card");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "section-heading": {
    name: "section-heading",
    type: "registry:component",
    title: "Section Heading",
    description:
      "A component that standardizes heading typography and spacing. This component includes a pre-heading label, main heading, and body text in different layout variants.",
    registryDependencies: ["TODO:/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/components/section-heading.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/components/section-heading");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "star-rating": {
    name: "star-rating",
    type: "registry:component",
    title: "Star Rating",
    description:
      "A component that displays ratings with stars and an optional label. This component builds trust with visual feedback.",
    registryDependencies: ["TODO:/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/components/star-rating.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/components/star-rating");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "avatar-stack-example": {
    name: "avatar-stack-example",
    type: "registry:example",
    title: "Avatar Stack Example",
    description: "",
    registryDependencies: ["avatar", "@shadcraft/avatar-stack"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/avatar-stack-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/avatar-stack-example");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "heading-example": {
    name: "heading-example",
    type: "registry:example",
    title: "Heading Example",
    description: "",
    registryDependencies: ["@shadcraft/heading"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/heading-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/heading-example");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "marquee-example": {
    name: "marquee-example",
    type: "registry:example",
    title: "Marquee Example",
    description: "",
    registryDependencies: ["@shadcraft/marquee"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/marquee-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/marquee-example");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "page-heading-example": {
    name: "page-heading-example",
    type: "registry:example",
    title: "Page Heading Example",
    description: "",
    registryDependencies: ["@shadcraft/page-heading"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/page-heading-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/page-heading-example");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "placeholder-logo-example": {
    name: "placeholder-logo-example",
    type: "registry:example",
    title: "Placeholder Logo Example",
    description: "",
    registryDependencies: ["@shadcraft/placeholder-logo"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/placeholder-logo-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/placeholder-logo-example");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "profile-card-example": {
    name: "profile-card-example",
    type: "registry:example",
    title: "Profile Card Example",
    description: "",
    registryDependencies: ["@shadcraft/profile-card"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/profile-card-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/profile-card-example");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "section-heading-example": {
    name: "section-heading-example",
    type: "registry:example",
    title: "Section Heading Example",
    description: "",
    registryDependencies: ["@shadcraft/section-heading"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/section-heading-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/section-heading-example");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "star-rating-example": {
    name: "star-rating-example",
    type: "registry:example",
    title: "Star Rating Example",
    description: "",
    registryDependencies: ["@shadcraft/star-rating"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/star-rating-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/star-rating-example");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "tagline-example": {
    name: "tagline-example",
    type: "registry:example",
    title: "Tagline Example",
    description: "",
    registryDependencies: ["@shadcraft/tagline"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/tagline-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/tagline-example");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "use-carousel": {
    name: "use-carousel",
    type: "registry:hook",
    title: "",
    description: "",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/pro-marketing/hooks/use-carousel.ts",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/hooks/use-carousel");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "use-click-outside": {
    name: "use-click-outside",
    type: "registry:hook",
    title: "",
    description: "",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/pro-marketing/hooks/use-click-outside.ts",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/hooks/use-click-outside");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "use-mobile": {
    name: "use-mobile",
    type: "registry:hook",
    title: "",
    description: "",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/pro-marketing/hooks/use-mobile.ts",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/hooks/use-mobile");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
};
