/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

type RegistryItemWithComponent = RegistryItem & {
  component: React.LazyExoticComponent<React.ComponentType<any>>;
};

export const Index: Record<string, RegistryItemWithComponent> = {
  "avatar-stack": {
    name: "avatar-stack",
    type: "registry:ui",
    title: "Avatar Stack",
    description: "A component that stacks and overlaps a list of avatars.",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/ui/avatar-stack.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/ui/avatar-stack");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  marquee: {
    name: "marquee",
    type: "registry:ui",
    title: "Marquee",
    description:
      "A component that displays a list of items in a horizontal or vertical scrolling motion.",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/ui/marquee.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/ui/marquee");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  tagline: {
    name: "tagline",
    type: "registry:ui",
    title: "Tagline",
    description: "A component that displays a tagline with different variants.",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/ui/tagline.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/ui/tagline");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "page-heading": {
    name: "page-heading",
    type: "registry:component",
    title: "Page Heading",
    description:
      "A component that acts as the text-focused version of a hero banner. This component combines a pre-heading label, an H1 heading, supporting description text, and call-to-action buttons.",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/components/page-heading.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/components/page-heading");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "placeholder-logo": {
    name: "placeholder-logo",
    type: "registry:component",
    title: "Placeholder Logo",
    description:
      "A component for that can be replaced with your brand's main logo. This component ensures layouts stay consistent before brand assets are applied.",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/components/placeholder-logo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/components/placeholder-logo");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "profile-card": {
    name: "profile-card",
    type: "registry:component",
    title: "Profile Card",
    description:
      "An extension of the avatar component with more details on the individual. Good for blog posts etc.",
    registryDependencies: ["avatar", "https://shadcraft-free.vercel.app/r/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/components/profile-card.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/components/profile-card");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "section-heading": {
    name: "section-heading",
    type: "registry:component",
    title: "Section Heading",
    description:
      "A component that standardizes heading typography and spacing. This component includes a pre-heading label, main heading, and body text in different layout variants.",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/components/section-heading.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/components/section-heading");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "star-rating": {
    name: "star-rating",
    type: "registry:component",
    title: "Star Rating",
    description:
      "A component that displays ratings with stars and an optional label. This component builds trust with visual feedback.",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/components/star-rating.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/components/star-rating");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "avatar-stack-demo": {
    name: "avatar-stack-demo",
    type: "registry:example",
    title: "Avatar Stack Demo",
    description: "",
    registryDependencies: ["avatar", "https://shadcraft-free.vercel.app/r/avatar-stack.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/avatar-stack-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/avatar-stack-demo");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "marquee-demo": {
    name: "marquee-demo",
    type: "registry:example",
    title: "Marquee Demo",
    description: "",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/marquee.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/marquee-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/marquee-demo");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "page-heading-demo": {
    name: "page-heading-demo",
    type: "registry:example",
    title: "Page Heading Demo",
    description: "",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/page-heading.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/page-heading-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/page-heading-demo");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "placeholder-logo-demo": {
    name: "placeholder-logo-demo",
    type: "registry:example",
    title: "Placeholder Logo Demo",
    description: "",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/placeholder-logo.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/placeholder-logo-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/placeholder-logo-demo");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "profile-card-demo": {
    name: "profile-card-demo",
    type: "registry:example",
    title: "Profile Card Demo",
    description: "",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/profile-card.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/profile-card-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/profile-card-demo");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "section-heading-demo": {
    name: "section-heading-demo",
    type: "registry:example",
    title: "Section Heading Demo",
    description: "",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/section-heading.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/section-heading-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/section-heading-demo");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "star-rating-demo": {
    name: "star-rating-demo",
    type: "registry:example",
    title: "Star Rating Demo",
    description: "",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/star-rating.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/star-rating-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/star-rating-demo");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "tagline-demo": {
    name: "tagline-demo",
    type: "registry:example",
    title: "Tagline Demo",
    description: "",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/tagline.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/tagline-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/tagline-demo");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "use-carousel": {
    name: "use-carousel",
    type: "registry:hook",
    title: "",
    description: "",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/pro-marketing/hooks/use-carousel.ts",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/hooks/use-carousel");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "use-click-outside": {
    name: "use-click-outside",
    type: "registry:hook",
    title: "",
    description: "",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/pro-marketing/hooks/use-click-outside.ts",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/hooks/use-click-outside");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "use-mobile": {
    name: "use-mobile",
    type: "registry:hook",
    title: "",
    description: "",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/pro-marketing/hooks/use-mobile.ts",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/hooks/use-mobile");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
};
