/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

type RegistryItemWithComponent = RegistryItem & {
  component: React.LazyExoticComponent<React.ComponentType<any>>;
};

export const Index: Record<string, RegistryItemWithComponent> = {
  "avatar-stack": {
    name: "avatar-stack",
    type: "registry:ui",
    title: "Avatar Stack",
    description: "A component that stacks and overlaps a list of avatars.",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/ui/avatar-stack.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: null,
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  marquee: {
    name: "marquee",
    type: "registry:ui",
    title: "Marquee",
    description:
      "A component that displays a list of items in a horizontal or vertical scrolling motion.",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/ui/marquee.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: null,
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "page-heading": {
    name: "page-heading",
    type: "registry:ui",
    title: "Page Heading",
    description:
      "A component that acts as the text-focused version of a hero banner. This component combines a pre-heading label, an H1 heading, supporting description text, and call-to-action buttons.",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/ui/page-heading.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: null,
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "placeholder-logo": {
    name: "placeholder-logo",
    type: "registry:ui",
    title: "Placeholder Logo",
    description:
      "A component for that can be replaced with your brand's main logo. This component ensures layouts stay consistent before brand assets are applied.",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/ui/placeholder-logo.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: null,
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "profile-card": {
    name: "profile-card",
    type: "registry:ui",
    title: "Profile Card",
    description:
      "An extension of the avatar component with more details on the individual. Good for blog posts etc.",
    registryDependencies: ["avatar", "https://shadcraft-free.vercel.app/r/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/ui/profile-card.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: null,
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "section-heading": {
    name: "section-heading",
    type: "registry:ui",
    title: "Section Heading",
    description:
      "A component that standardizes heading typography and spacing. This component includes a pre-heading label, main heading, and body text in different layout variants.",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/ui/section-heading.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: null,
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "star-rating": {
    name: "star-rating",
    type: "registry:ui",
    title: "Star Rating",
    description:
      "A component that displays ratings with stars and an optional label. This component builds trust with visual feedback.",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/ui/star-rating.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: null,
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  tagline: {
    name: "tagline",
    type: "registry:ui",
    title: "Tagline",
    description: "A component that displays a tagline with different variants.",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/ui/tagline.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: null,
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "banner-10": {
    name: "banner-10",
    type: "registry:block",
    title: "Banner 10",
    description: "",
    registryDependencies: ["button", "https://shadcraft-free.vercel.app/r/index.json"],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/banners/10/index.tsx",
        type: "registry:component",
        target: "components/banner-10.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/banners/10/index.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["banners"],
    meta: { bundle: "pro-marketing" },
  },
  "benefits-13": {
    name: "benefits-13",
    type: "registry:block",
    title: "Benefits 13",
    description: "",
    registryDependencies: [
      "card",
      "https://shadcraft-free.vercel.app/r/section-heading.json",
      "https://shadcraft-free.vercel.app/r/index.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/benefits/13/index.tsx",
        type: "registry:component",
        target: "components/benefits-13.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/benefits/13/index.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["benefits"],
    meta: { bundle: "pro-marketing" },
  },
  "contact-11": {
    name: "contact-11",
    type: "registry:block",
    title: "Contact 11",
    description: "",
    registryDependencies: [
      "button",
      "label",
      "input",
      "textarea",
      "checkbox",
      "https://shadcraft-free.vercel.app/r/section-heading.json",
      "https://shadcraft-free.vercel.app/r/index.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/contact/11/index.tsx",
        type: "registry:component",
        target: "components/contact-11.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/contact/11/index.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["contact"],
    meta: { bundle: "pro-marketing" },
  },
  "cta-9": {
    name: "cta-9",
    type: "registry:block",
    title: "CTA 9",
    description: "",
    registryDependencies: [
      "button",
      "https://shadcraft-free.vercel.app/r/section-heading.json",
      "https://shadcraft-free.vercel.app/r/index.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/cta/9/index.tsx",
        type: "registry:component",
        target: "components/cta-9.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/cta/9/index.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["cta"],
    meta: { bundle: "pro-marketing" },
  },
  "faqs-4": {
    name: "faqs-4",
    type: "registry:block",
    title: "FAQs 4",
    description: "",
    registryDependencies: [
      "accordion",
      "separator",
      "https://shadcraft-free.vercel.app/r/section-heading.json",
      "https://shadcraft-free.vercel.app/r/index.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/faqs/4/index.tsx",
        type: "registry:component",
        target: "components/faqs-4.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/faqs/4/index.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["faqs"],
    meta: { bundle: "pro-marketing" },
  },
  "footer-4": {
    name: "footer-4",
    type: "registry:block",
    title: "Footer 4",
    description: "",
    registryDependencies: [
      "separator",
      "https://shadcraft-free.vercel.app/r/placeholder-logo.json",
      "https://shadcraft-free.vercel.app/r/index.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/footers/4/index.tsx",
        type: "registry:component",
        target: "components/footer-4.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/footers/4/index.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["footers"],
    meta: { containerClassName: "min-h-svh content-end", bundle: "pro-marketing" },
  },
  "newsletter-signup-5": {
    name: "newsletter-signup-5",
    type: "registry:block",
    title: "Newsletter Signup 5",
    description: "",
    registryDependencies: [
      "button",
      "input",
      "https://shadcraft-free.vercel.app/r/section-heading.json",
      "https://shadcraft-free.vercel.app/r/index.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/newsletter-signup/5/index.tsx",
        type: "registry:component",
        target: "components/newsletter-signup-5.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/newsletter-signup/5/index.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["newsletter-signup"],
    meta: { bundle: "pro-marketing" },
  },
  "team-6": {
    name: "team-6",
    type: "registry:block",
    title: "Team 6",
    description: "",
    registryDependencies: [
      "https://shadcraft-free.vercel.app/r/section-heading.json",
      "https://shadcraft-free.vercel.app/r/profile-card.json",
      "https://shadcraft-free.vercel.app/r/index.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/team/6/index.tsx",
        type: "registry:component",
        target: "components/team-6.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/team/6/index.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["team"],
    meta: { bundle: "pro-marketing" },
  },
  "testimonials-11": {
    name: "testimonials-11",
    type: "registry:block",
    title: "Testimonials 11",
    description: "",
    registryDependencies: [
      "card",
      "https://shadcraft-free.vercel.app/r/section-heading.json",
      "https://shadcraft-free.vercel.app/r/profile-card.json",
      "https://shadcraft-free.vercel.app/r/index.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/testimonials/11/index.tsx",
        type: "registry:component",
        target: "components/testimonials-11.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/testimonials/11/index.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["testimonials"],
    meta: { bundle: "pro-marketing" },
  },
  "pricing-8": {
    name: "pricing-8",
    type: "registry:block",
    title: "Pricing 8",
    description: "",
    registryDependencies: [
      "card",
      "button",
      "tooltip",
      "https://shadcraft-free.vercel.app/r/section-heading.json",
      "https://shadcraft-free.vercel.app/r/index.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/pricing/8/index.tsx",
        type: "registry:component",
        target: "components/pricing-8.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/pricing/8/index.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["pricing"],
    meta: { bundle: "pro-marketing" },
  },
  "top-navigation-5": {
    name: "top-navigation-5",
    type: "registry:block",
    title: "Top Navigation 5",
    description: "",
    registryDependencies: [
      "button",
      "https://shadcraft-free.vercel.app/r/placeholder-logo.json",
      "https://shadcraft-free.vercel.app/r/use-click-outside.json",
      "https://shadcraft-free.vercel.app/r/use-mobile.json",
      "https://shadcraft-free.vercel.app/r/index.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/top-navigation/5/index.tsx",
        type: "registry:component",
        target: "components/top-navigation-5.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/top-navigation/5/index.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["top-navigation"],
    meta: { bundle: "pro-marketing" },
  },
  "avatar-stack-demo": {
    name: "avatar-stack-demo",
    type: "registry:example",
    title: "Avatar Stack Demo",
    description: "",
    registryDependencies: ["avatar", "https://shadcraft-free.vercel.app/r/avatar-stack.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/avatar-stack-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/avatar-stack-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "marquee-demo": {
    name: "marquee-demo",
    type: "registry:example",
    title: "Marquee Demo",
    description: "",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/marquee.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/marquee-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/marquee-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "page-heading-demo": {
    name: "page-heading-demo",
    type: "registry:example",
    title: "Page Heading Demo",
    description: "",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/page-heading.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/page-heading-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/page-heading-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "placeholder-logo-demo": {
    name: "placeholder-logo-demo",
    type: "registry:example",
    title: "Placeholder Logo Demo",
    description: "",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/placeholder-logo.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/placeholder-logo-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/placeholder-logo-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "profile-card-demo": {
    name: "profile-card-demo",
    type: "registry:example",
    title: "Profile Card Demo",
    description: "",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/profile-card.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/profile-card-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/profile-card-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "section-heading-demo": {
    name: "section-heading-demo",
    type: "registry:example",
    title: "Section Heading Demo",
    description: "",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/section-heading.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/section-heading-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/section-heading-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "star-rating-demo": {
    name: "star-rating-demo",
    type: "registry:example",
    title: "Star Rating Demo",
    description: "",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/star-rating.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/star-rating-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/star-rating-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "tagline-demo": {
    name: "tagline-demo",
    type: "registry:example",
    title: "Tagline Demo",
    description: "",
    registryDependencies: ["https://shadcraft-free.vercel.app/r/tagline.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/tagline-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/tagline-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "use-carousel": {
    name: "use-carousel",
    type: "registry:hook",
    title: "",
    description: "",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/pro-marketing/hooks/use-carousel.ts",
        type: "registry:hook",
        target: "",
      },
    ],
    component: null,
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "use-click-outside": {
    name: "use-click-outside",
    type: "registry:hook",
    title: "",
    description: "",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/pro-marketing/hooks/use-click-outside.ts",
        type: "registry:hook",
        target: "",
      },
    ],
    component: null,
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "use-mobile": {
    name: "use-mobile",
    type: "registry:hook",
    title: "",
    description: "",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/pro-marketing/hooks/use-mobile.ts",
        type: "registry:hook",
        target: "",
      },
    ],
    component: null,
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
};
